"resources" 
{
"maps\de_lost2.bsp" "file"
"maps\de_lost2.nav" "file"
"maps\de_lost2.res" "file"
"sound\nippersounds\lst_beep1.wav" "file"
"sound\nippersounds\lst_beep2.wav" "file"
"sound\nippersounds\lst_blastdoorsup.wav" "file"
"sound\nippersounds\lst_desmond.wav" "file"
"sound\nippersounds\lst_dharma.wav" "file"
"sound\nippersounds\lst_keyhits.wav" "file"
"sound\nippersounds\lst_lockdown1.wav" "file"
"sound\nippersounds\lst_lockdown2.wav" "file"
"sound\nippersounds\lst_lockebreakdown.wav" "file"
"sound\nippersounds\lst_lockedestiny.wav" "file"
"sound\nippersounds\lst_lost_intro.wav" "file"
"sound\nippersounds\lst_smoke1.wav" "file"
"sound\nippersounds\lst_smoke2.wav" "file"
"sound\nippersounds\lst_smokeloop.wav" "file"
"sound\nippersounds\lst_system_failure.wav" "file"
"sound\nippersounds\lst_voices1.wav" "file"
"sound\nippersounds\lst_voices2.wav" "file"
"sound\nippersounds\lst_voices3.wav" "file"
"sound\nippersounds\lst_waltwaltwalt.wav" "file"
"sound\nippersounds\lst_em_discharge.mp3" "file"
"sound\nippersounds\makeyourownmusic.mp3" "file"
}